### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by jasons1234** [Im-Stevemmmmm/the-blue-hats-server#13]
i cant find the start-server.bat file to start the server

**Comment by Im-Stevemmmmm** [comment]
Hello! Sorry for the very late response as I decided to take a break on maintaining the project.

I have downloaded `The-Blue-Hats-Server.zip` binary from the v0.1 Alpha release [here](https://github.com/Im-Stevemmmmm/the-blue-hats-server/releases). There does seem to be a `start-server.bat` file. Try re downloading it. If for some reason it's still not there, start the server using the command `java -jar -Xmx2G -Xms512M spigot.jar nogui
`.
